{% set version = "2.1.5" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gbm
  version: {{ version|replace("-", "_") }}

source:
  fn: gbm_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/gbm_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gbm/gbm_{{ version }}.tar.gz
  sha256: 06fbde10639dfa886554379b40a7402d1f1236a9152eca517e97738895a4466f

build:
  merge_build_host: True  # [win]
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: knitr, pdp, RUnit, splines, viridis
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{ compiler('m2w64_c') }}        # [win]
    - {{ compiler('m2w64_cxx') }}        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-gridextra
    - r-lattice
    - r-survival

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-gridextra
    - r-lattice
    - r-survival

test:
  commands:
    - $R -e "library('gbm')"           # [not win]
    - "\"%R%\" -e \"library('gbm')\""  # [win]

about:
  home: https://github.com/gbm-developers/gbm
  license: GPL (>= 2)
  summary: An implementation of extensions to Freund and Schapire's AdaBoost  algorithm and Friedman's
    gradient boosting machine. Includes regression  methods for least squares, absolute
    loss, t-distribution loss, quantile  regression, logistic, multinomial logistic,
    Poisson, Cox proportional hazards  partial likelihood, AdaBoost exponential loss,
    Huberized hinge loss, and  Learning to Rank measures (LambdaMart). Originally developed
    by Greg Ridgeway.
  license_family: GPL3

extra:
  recipe-maintainers:
    - conda-forge/r
    - dpryan79
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
