travis:
  secure:
    BINSTAR_TOKEN: KJ4PPuECILzS9O77yowsbWp0F1O9I/XVZMzLSjlDBvvBLiVmSeLbdw0/ZBAnorp+YhSmEbewIPPnzXplEjn3Ke6mz4KdWzG/AhDaJKitEGoN8zGLkyr0Q1YHC+Ppw+DWBwuAZFjN75rUIIJjWSTrZm6tlBy+ufxSGgcEgaiu5T0BEK70xyo9iX5uqknbU4x1Ay1cb8vXed7+hYxlVgfext6r0vNiQ1NpL4j6LRV4d+G2k2/F6i//DR9eNEClboNxouW7fISjxasrvWe4UBsoh4gX8cPAvsAakoOk9NoKuRVZBk5eWRWHgkqM51bxckR4E0oH5E5w0iwOvxw2rQBorc8wHopejiyq/M8fWpwYirk6stsZWkwyKz70o/oKyVnSY7Qs0ZYViOWghs8zt6gjm6pR91yvOXwRQ+AElQ4mgYd8RQ7DY9R1GmTp1ZqeXiW9AR4c7WTd8j8KOe/uo0x7z2EuVEwCVV8V4WbsQTvAydkforNd3ZpvcHBAHHji7PlnR+CunO/G7IgMml25gseUO7FOvUkRMgoXA8LHezNpKGEs6IXEKhdqtjLNYu0bGsKl77uUFXk0E4HFURBa+T/bvMcOwClS3f/VG3WGDnJ9omfzNA2ln/QqmzXHbY4gD4RqCSP87ujJPHnywhfzjuRZDizZHwmP/Xi87i67tkLgA5Y=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
