appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: qkhDomG+u9MauqFUdnOBZtQqsaqvERrrL+POkYqYN8KmZq+2iJd0JVw2nsBayF/zNfdjRn91k97CUK2G2ud+rATDJ6scc2lZnWQux0Payl7Xzl3SMLT4GE0CHC3SJc2sdZ6I6ajoH8laJfEjA+fTLNRgc46t2q0wAGjILxPeahGlOPN2TLiqpWesa/HrJeALVLizezfAclsBuIMNom3PEl2R0JiAgIrcgdsdZTxru86kBJeqnse0a6a5Eb50e0sxL+ucVQM3L0mrm/5BWY77bjjg+WW2vHiwGPG28NII+AlL9sSs+KLvQtvOA56aL2qod3hHQNukIfYAgFUeZKlGHecdUibSVvdC+jyRWDFJZuo3ihvMe2xmugTZXJ7Xy1wQUE2Tz7AiudyznRC6hBtJyd0J9/sc2Q+CtdbwbGgoGLBPeeiJW9b88vlPZQfby2EO5wx8KlXG8QEJASSBKsqp0+QtcpYC8vSdMDVYtnxNQz0Iy2CamBQNdk5cvkOGzy84puH6KrmexuVwaddPivgFb1pvBs2wT/xYG3F3TFQi5CwhYQlSD5PMhivE5W9PZDC5LuinCXp5/T6jCFB7f85k9DxGjN2i29G0ltBlG2GXFNOBnyXSix39f/AsOx9sN4E/vtvXuzBGhPtjc62tg/+59LV3PYX2zF3hsYiG9sJ5zgU=}
